Revert "base: add CPU info overlay [1/2] Change-Id: I8e2fd81edd8499eea2b1a6de8c042938387b33ef Signed-off-by: mydongistiny <jaysonedson@gmail.com>  a7.1.2"
This reverts commit 6d04601f858647573dc1fc7d4925c569f25bb18a.

ERROR: /home/kevin/CandyTest/frameworks/base/packages/SystemUI/src
/com/android/systemui/BootReceiver.java:44: START_SCREEN_STATE_SER
VICE cannot be resolved or is not a field 
ERROR: /home/kevin/CandyTest/frameworks/base/packages/SystemUI/src
/com/android/systemui/BootReceiver.java:45: com.android.systemui.s
creenstate cannot be resolved to a type

Change-Id: I76d9b3b75b5a88577526fcb4c71e46005aa55472